# Welcome to Jekyll!
#

# Site settings
title: Adam Dix
description: Artist and object maker
owner: Adam Dix # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
# baseurl: "" the subpath of your site, e.g. /blog
url: "http://www.adamdix.com" # the base hostname & protocol for your site
collections:
  works:
    output: true
    permalink: /works/:path/
    output_ext: html

defaults:
  -
    scope:
      path: ""
      type: "works"
    values:
      title: ""
      description: ""
      year: ""
      size: ""
      thumbnail: ""
      layout: works

social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://www.instagram.com/adammdix/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
